03 mongodb
yarikgorpl/nodejs-homework-rest-api pull request #2
Opened 2023-09-16 14:03 UTC by yarikgorpl

Добрий день. Подивіться будь ласка що я наробив). Не можу зрозуміти,чому виникають помилки при patch,post. І перевірте HttpError чи я правильно зробив,можливо через те помилки.Дякую.

2023-09-16 14:50 UTC, KhYulian commented on utils/validation/contactValidationSchemas.js
>  });
Виносьте схеми валідації окремо e.g. /utils/validation/contactValidationSchemas.js

2023-09-16 14:51 UTC, KhYulian requested changes
залишив комент

2023-09-16 14:51 UTC, KhYulian commented
HttpError в порядку. яка саме помилка виникає?

2023-09-16 17:38 UTC, yarikgorpl commented on utils/validation/contactValidationSchemas.js
>  });
Тобто потрібно схему валідації mongoose винести окремо?Бо в відео навпаки оекомендованоїх об'єднати. Зараз ці схеми лежать в окремій дирректорії utils

2023-09-17 07:49 UTC, KhYulian approved these changes
Чудова робота

2023-09-17 07:49 UTC, merged